### ISSUE TITLE
代码复制的操作是如何进行的？

### ISSUE THREAD

**Issue by xiaolengwu** [irisguanhong/irisguanhong.github.io#1]
Fork 主题博客的源码仓库（如果是使用这个模板博客，则是新建仓库，然后从学员仓库主目录中将 3Jekyll 文件夹下的 Jekyll Blog Theme 代码复制过去）。
代码复制的操作是如何进行的？
我的微信是wgxlw2011，方便加下吗？

**Comment by irisguanhong** [comment]
你好。我是这样做的：
1. 新建了repository irisguanhong.github.io，并没有勾选自动创建readme.md
2. 把这个空的repository clone到本地。
3. 把本地irisguanhong/hacker/3 jerkll/jerkll blog theme里面的所有文件，直接copy到本地的irisguanhong.github.io 文件夹下。
4. commit change到github web端。
5. 修改了 _config.yml里面的内容 --也就是customize的一部分
6. 再commit 然后在我本地的github desktop里面选择了 publish 发布
然后 irisguanhong.github.io 生效了

**Comment by xiaolengwu** [comment]
非常感谢，按照你的指导，搞定了
